Feature/tech 8065
indi-gg/kgen-airdrop pull request #6
Opened 2024-05-09 12:38 UTC by Sameer-Begh

Campaign Listing Page with Cards and Footer

2024-05-09 12:59 UTC, shelly19gkmit commented on src/app/airdrop/page.tsx
> +      }}
Avoid inline styles

2024-05-09 12:59 UTC, shelly19gkmit commented on src/app/airdrop/page.tsx
> +            </Grid.Col>
Don't use "index" in key, use some other unique value coming from dummyMap

2024-05-09 13:00 UTC, shelly19gkmit commented on src/app/page.tsx
> +    </>
Remove unnecessary <></>

2024-05-09 13:00 UTC, shelly19gkmit commented on src/assets/images/Banner.png
Avoid using images in MBs

2024-05-09 13:00 UTC, shelly19gkmit commented on src/components/campaign_banner/CampaignBanner.module.css
> +  }
Remove comments if not needed

2024-05-09 13:01 UTC, shelly19gkmit commented on src/components/campaign_banner/CampaingBanner.tsx
> +}
Manage types in separate files, it would keep component files clean

2024-05-09 13:02 UTC, shelly19gkmit commented on src/components/campaign_banner/CampaingBanner.tsx
> +import { FC, useState } from "react";
Why we have campaign_banner component?

2024-05-09 13:02 UTC, shelly19gkmit commented on src/components/timer_count_down/CountDown.tsx
> +import { useRef, useState, useEffect } from "react";
Why using format including _ ?"timer_count_down"

2024-05-09 13:03 UTC, shelly19gkmit commented on src/components/ui/Cards/HexagonCard/HexagonCard.module.css
> +.controls {
Why 2 files for stylings? HexagonCard.module.css and HexagonCard.css

2024-05-09 13:04 UTC, shelly19gkmit commented on src/components/ui/button/Button.stories.ts
> +// import Button from '../../ui/button/index';
Remove unnecessary comments

2024-05-09 13:09 UTC, shelly19gkmit commented on src/translations/en.ts
> +    BUILDPAGE_DESC:
Maintain simple structure, don't create variables for all strings.
Idea is to developer should understand strings and data easily just by looking at the structure-

Example -> For home-
  if (page === HOME) {
    return {
      title: "KGeN - The most powerful gamer reputation engine",
      description:
        "Discover KGeN, where gaming meets the future. Elevate your gaming experience by building a gamer identity with a reputation engine powered by a gamer data chain owned by you"
    };
  }

2024-05-09 13:12 UTC, shelly19gkmit commented on src/translations/en.ts
> +    IMAGE_TAB_CONNECT: "Connect",
Plz maintain objects instead of adding variables for every strings. It will results in very lengthy file which is not recommanded.

It should be like-
If we are adding for footer
Example-

const FOOTER={
TITLE: "Title",
}
const HOME={
TITLE: "Title",
}

So that if file exceeds certain length we can create divide/separate these objects.

2024-05-09 13:13 UTC, shelly19gkmit requested changes
High level of refactoring is needed.

2024-05-10 04:43 UTC, mandeepatindigg commented on src/app/airdrop/page.tsx
> +import '../../components/ui/Cards/HexagonCard/HexagonCard.css';
keep it absolute import using @

2024-05-10 04:44 UTC, mandeepatindigg commented on src/app/globals.css
> +    #1a2d32 100%
make colors variables in css file and use by names

2024-05-10 04:47 UTC, mandeepatindigg commented on src/components/campaign_banner/CampaignBanner.module.css
> +.controls {
keep logo file with background

2024-05-10 04:49 UTC, mandeepatindigg commented on src/components/campaign_banner/CampaingBanner.tsx
> +              }}
inline styles

2024-05-10 04:49 UTC, mandeepatindigg commented on src/components/campaign_banner/CustomCarousel.tsx
> +            fontWeight: 400,
inline styles

2024-05-10 04:51 UTC, mandeepatindigg commented on src/components/footer/Footer.tsx
> +        style={{ "--sectionHeight": sectionHeight + "px" } as any}
iinline styling

2024-05-10 04:52 UTC, mandeepatindigg commented on src/components/header/Header.module.scss
> +//  border: 2px solid red;
commernted code

2024-05-10 04:52 UTC, mandeepatindigg commented on src/components/header/Header.module.scss
> +      // }
commented code

2024-05-10 09:16 UTC, mandeepatindigg commented on src/components/campaingbanner/CustomCarousel.tsx
> +import React, {FC} from 'react';
change to index.tsx

2024-05-10 09:17 UTC, mandeepatindigg commented on src/components/campaingbanner/CampaignBanner.module.css
> +.carousel {
change all files name to camelCase, keep first letter small

2024-05-10 09:18 UTC, mandeepatindigg commented on src/components/campaingbanner/CustomCarousel.tsx
> +    <Box>
why added this <Box> not needed

2024-05-10 09:22 UTC, shelly19gkmit commented on src/components/campaingbanner/CustomCarousel.tsx
> +import React, {FC} from 'react';
Spelling mistake -> campaingbanner, should be campaignBanner

2024-05-10 09:22 UTC, shelly19gkmit commented on src/components/campaingbanner/index.tsx
> +import {Box, Title} from '@mantine/core';
Spelling mistake -> campaingbanner

2024-05-10 09:24 UTC, mandeepatindigg commented on src/components/ui/Cards/campaigncard/index.tsx
> +import React from 'react';
pls keep name to camelCase

2024-05-10 09:25 UTC, mandeepatindigg commented on src/components/ui/Cards/campaigncard/index.tsx
> +          <Text className="sub-title">CITIZEN CONFLICT</Text>
strinf

2024-05-10 09:25 UTC, mandeepatindigg commented on src/components/ui/Cards/campaigncard/index.tsx
> +      <>
pls change to Box dont use fragments

2024-05-10 09:26 UTC, mandeepatindigg commented on src/components/ui/button/button.css
> +} */
remove commented code

2024-05-10 09:40 UTC, Sameer-Begh commented on src/components/campaign_banner/CampaignBanner.module.css
> +.controls {
done

2024-05-10 09:41 UTC, Sameer-Begh commented on src/components/campaign_banner/CampaingBanner.tsx
> +          flexDirection: "column",
done

2024-05-10 09:53 UTC, Sameer-Begh commented on src/components/campaingbanner/CustomCarousel.tsx
> +    <Box>
done

2024-05-10 09:54 UTC, Sameer-Begh commented on src/components/ui/Cards/campaigncard/index.tsx
> +          <Text className="sub-title">CITIZEN CONFLICT</Text>
Its a dynamic content

2024-05-10 09:54 UTC, Sameer-Begh commented on src/components/ui/button/button.css
> +} */
done

2024-05-10 10:54 UTC, shrutiIndigg approved these changes

2024-05-10 10:55 UTC, merged