Add profile section
indi-gg/kgen-airdrop pull request #8
Opened 2024-05-10 12:37 UTC by supthefuhrer1

2024-05-10 16:15 UTC, shelly19gkmit commented on src/app/profile/page.tsx
> +import {Grid} from '@mantine/core';
use absolute path for assets

2024-05-10 16:16 UTC, shelly19gkmit commented on src/app/profile/page.tsx
> +}
Create a separate file for maintaining types in Profile folder.

2024-05-10 16:19 UTC, shelly19gkmit commented on src/app/profile/page.tsx
> +            </Grid.Col>
Create reusable Select component

2024-05-10 16:24 UTC, shelly19gkmit commented on src/app/profile/page.tsx
> +          )}
create function

2024-05-10 16:27 UTC, shelly19gkmit commented on src/app/profile/page.tsx
> +              setIsSocialConnected={setIsMetaMaskConnected}
Divide Profile components into 4 different components->
Profile -> profile
Username -> profile/username
PROFILE DETAILS -> profile/details
CONNECT ACCOUNTS -> profile/connectAccounts

Create array and maintain these logics like this
const socialConnections = [
  {
    label: SOCIAL.TWITTER,
    isSocialConnected: isTwitterConnected,
    setIsSocialConnected: setIsTwitterConnected,
    socialId: twitterId,
  },
  {
    label: SOCIAL.DISCORD,
    isSocialConnected: isDiscordConnected,
    setIsSocialConnected: setIsDiscordConnected,
    socialId: discordId,
  },
  {
    label: SOCIAL.GOOGLE,
    isSocialConnected: isGoogleConnected,
    setIsSocialConnected: setIsGoogleConnected,
    socialId: googleId,
  },
  {
    label: SOCIAL.METAMASK,
    isSocialConnected: isMetaMaskConnected,
    setIsSocialConnected: setIsMetaMaskConnected,
    socialId: metamaskId,
    divider: false,
  },
];

const renderedConnections = socialConnections.map(({ label, isSocialConnected, setIsSocialConnected, socialId, divider = true }, index) => (
  <SocialConnect
    key={index}
    label={label}
    isSocialConnected={isSocialConnected}
    setIsSocialConnected={setIsSocialConnected}
    socialId={socialId}
    divider={divider}
  />
));

2024-05-10 16:27 UTC, shelly19gkmit commented on src/components/CountryPicker/index.tsx
> +      //   variant='default'
remove constant

2024-05-10 16:27 UTC, shelly19gkmit commented on src/components/CountryPicker/index.tsx
> +      }}
define styles separately and use it here

2024-05-10 16:28 UTC, shelly19gkmit commented on src/components/CountryPicker/index.tsx
> +      disabled={readOnly}
maintain function

2024-05-10 16:29 UTC, shelly19gkmit commented on src/utils/helpers.tsx
> +
Helper file shouldn't be tsx, it should only contain logics not any components. Plz make this a separate component in components folder

2024-05-10 16:30 UTC, shelly19gkmit requested changes
Refactoring is needed, plz resolve the comments

2024-05-12 16:03 UTC, supratimmalakar commented on src/components/CountryPicker/index.tsx
> +      }}
Already refactored and fixed the Country Picker component in the Login modal pr. Will take a pull once that pr is merged

2024-05-13 10:18 UTC, mandeepatindigg commented on src/themes/colors.ts
>    ['WHITE OP 0.4']: 'rgba(232, 243, 245, 0.4)', // OP : Opacity
duplicated devider

2024-05-13 10:44 UTC, shivams10 requested changes

2024-05-13 10:44 UTC, shivams10 commented on src/context/walletConnect.tsx
> +import {QueryClient, QueryClientProvider} from '@tanstack/react-query';
We will be using RTK query and not tanstack query pls remove it

2024-05-13 11:03 UTC, merged